//! Compatibility target for Claude hooks generated by older wt releases.
//! Native releases no longer need a shell hook, but old installations can
//! still call this entrypoint during an update window.

use clap::Args;

#[derive(Debug, Clone, Args, Default)]
pub struct ClaudeHookArgs {
    #[arg(allow_hyphen_values = true, trailing_var_arg = true)]
    pub args: Vec<String>,
}

pub async fn run(_args: &ClaudeHookArgs) -> anyhow::Result<i32> {
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepts_legacy_register_and_unregister_arguments() {
        let command = ClaudeHookArgs::augment_args(clap::Command::new("_claude-hook"));
        assert!(
            command
                .clone()
                .try_get_matches_from(["_claude-hook", "register", "--path", "/tmp/a"])
                .is_ok()
        );
        assert!(
            command
                .try_get_matches_from(["_claude-hook", "unregister", "--slug", "x"])
                .is_ok()
        );
    }
}
