//! Compatibility entrypoint used by supervisor scripts generated by older wt.

use anyhow::Result;
use clap::Args;
use wt_dev::DevWorktree;

use crate::{context::AppContext, dev};

#[derive(Debug, Clone, Args)]
pub struct DevGiveupArgs {
    pub slug: String,
}

pub async fn run(context: &AppContext, args: &DevGiveupArgs) -> Result<i32> {
    if let Err(error) = run_inner(context, &args.slug).await {
        eprintln!("wt: dev give-up cleanup failed: {error:#}");
    }
    // The supervisor already recorded the crashed state; cleanup must not
    // replace its diagnostic pane with a second failure.
    Ok(0)
}

async fn run_inner(context: &AppContext, slug: &str) -> Result<()> {
    let record = context
        .repository
        .inventory(&context.cancellation)
        .await?
        .into_iter()
        .find(|row| !row.is_main && row.target.slug() == slug);
    let worktree = if let Some(record) = record {
        DevWorktree::from(&record)
    } else {
        let cwd = tokio::fs::canonicalize(&context.cwd).await;
        let root = tokio::fs::canonicalize(&context.config.paths.worktree_root).await;
        let main = tokio::fs::canonicalize(&context.config.paths.main_clone).await;
        let safe_cwd = match (cwd, root, main) {
            (Ok(cwd), Ok(root), Ok(main))
                if cwd != main
                    && cwd.starts_with(&root)
                    && cwd.file_name().and_then(|name| name.to_str()) == Some(slug) =>
            {
                Some(cwd)
            }
            _ => None,
        };
        let Some(safe_cwd) = safe_cwd else {
            eprintln!("wt: dev give-up ignored for {slug}: exact checkout is no longer present");
            return Ok(());
        };
        DevWorktree {
            slug: slug.to_owned(),
            path: safe_cwd,
            branch: String::new(),
        }
    };
    dev::service(context)?
        .legacy_give_up(&worktree, &context.cancellation)
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Args;

    #[test]
    fn compatibility_slug_is_a_single_argument() {
        let command = DevGiveupArgs::augment_args(clap::Command::new("_dev-giveup"));
        assert!(
            command
                .clone()
                .try_get_matches_from(["_dev-giveup", "feature-1"])
                .is_ok()
        );
        assert!(
            command
                .try_get_matches_from(["_dev-giveup", "one", "two"])
                .is_err()
        );
    }
}
