//! The in-app keymap is shared by rendering and bounded keyboard scrolling.
pub(crate) const LINES: &[&str] = &[
    "Navigation",
    "j / k, arrows    Move cursor",
    "g / G            First / last item",
    "PgUp / PgDn      Half-page navigation",
    "Space            Next row needing attention",
    "Tab              Fold / expand section",
    "Ctrl+D / Ctrl+U  Next / previous section",
    "Ctrl+J / Ctrl+K  Scroll details",
    "J / K            Reorder row or section",
    "",
    "Worktrees",
    "n / N            Create / create on selected branch",
    "o                Open editor",
    "d / c            Remove / clean (confirmation)",
    "a                Archive / restore",
    "h                Removed history; Enter restores",
    "t / T            Edit / regenerate title",
    "#                Edit issue identity",
    "l / L            File into section / rename section",
    "u / b            Work status / fork base",
    "R                Restack selected branch",
    "V                Show verification steps",
    "y                Copy picker",
    "",
    "Pull requests and links",
    "e / E            Mark ready / ship (confirmation)",
    "v                Choose reviewers; Space toggles",
    "f                Failed check logs",
    "! then m         Toggle merge when ready",
    "w / d on review  Check out / dismiss requested review",
    "p / gp / lp      Open PR / in GitHub / in Linear",
    "i / I / s        Issue / primary issue / stage",
    "",
    "Sessions and actions",
    "F10 / F11 / F12  Shell / diff / agent",
    "Shift+F10 / F11  Stop shell / diff (confirmation)",
    "; / Shift+F12    Resume or create agent session",
    "d in picker      Stop selected agent (confirmation)",
    "m / M            Manager session / commands",
    "!                Worktree action palette",
    "< / > / \\        wt / main / dotfiles commands",
    ", / . / /        wt / main / dotfiles session",
    "Shift+Tab        Cycle primary harness",
    "A / Ctrl+A       Pause global / selected automations",
    "Ctrl+Shift+A     Cancel queued automations",
    "",
    "Output",
    "'                Select activity / session / action log",
    "[ / ]            Previous / next stream",
    "Ctrl+Y / Ctrl+E  Scroll output up / down",
    "",
    "Application",
    "r                Refresh sources",
    "Ctrl+R           Clear derived caches and refetch",
    "P                Performance; r samples, i repeats",
    "?                Help; j/k scroll, g/G first/last",
    "q / Ctrl+C       Quit",
    "",
    "Esc / q / ? closes help",
];
