[package]
name = "wt-lifecycle"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
globset.workspace = true
libc.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
wt-config.workspace = true
wt-core.workspace = true
wt-platform.workspace = true
wt-store.workspace = true
wt-vcs.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
