[package]
name = "wt-stack"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
time.workspace = true
wt-config.workspace = true
wt-core.workspace = true
wt-github.workspace = true
wt-platform.workspace = true
wt-store.workspace = true
wt-vcs.workspace = true

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true

[lints]
workspace = true
