/**
 * Tmux supervision for wt actions. Sister module to `core/tmux.ts`:
 * that module owns the user-facing F10/F11/F12 attach flows, this one
 * owns the headless `<slug>-action` sessions that wrap action runs so
 * they survive wt restarts.
 *
 * # The wrapper
 *
 * Each action runs inside a small bash wrapper (`wt-action-wrapper.sh`,
 * generated to `~/.cache/wt/`) that:
 *   1. redirects stdout/stderr to per-run log files,
 *   2. on EXIT writes `done.json` with the inner command's exit code
 *      and a wall-clock timestamp.
 *
 * The wrapper survives wt restarts because tmux is its parent. When
 * the user kills an action via the TUI we update meta.json status to
 * `"killed"` first, then `tmux kill-session` — the wrapper's EXIT
 * trap fires and writes done.json so the boot reconciler always has
 * a sentinel to read.
 *
 * # Session naming
 *
 * One in-flight run per slug, session name `<slug>-action`. The
 * "one running per slug" invariant is enforced upstream in the
 * registry (it refuses to start a new run while one is active);
 * here we only ever attach/kill by that fixed name.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { createLogger } from "./logger.ts";

const log = createLogger("[action-tmux]");

const TMUX_SOCKET = "wt";
const ACTION_SUFFIX = "-action";

/**
 * Bash wrapper that supervises one action run. Generated verbatim to
 * disk on first launch so subsequent runs reuse it (and a wt upgrade
 * that changes this string atomically rolls forward). The wrapper:
 *
 *  - takes the run dir as $1, then the inner argv;
 *  - redirects stdout/stderr to `<run_dir>/stream.log` and
 *    `<run_dir>/stderr.log` (append, not truncate, so an unforeseen
 *    re-launch onto the same dir doesn't lose history — though by
 *    convention the registry never reuses a run dir);
 *  - on EXIT writes `<run_dir>/done.json` with the inner command's
 *    `exitCode`.
 *
 * Known limitation: stdout and stderr land in separate files, so the
 * tail (and the boot rehydration seed) can't reconstruct the exact
 * interleaving the user would have seen on a real terminal — stdout
 * lines appear first, then stderr, in each refresh. The pre-tmux
 * runner had the same coarse ordering (separate `consumeStdout` /
 * `consumeStderr` drains), so this isn't a regression. Folding to a
 * single `>>stream.log 2>&1` would fix the ordering at the cost of
 * losing the stderr distinction in the rendered output; not worth
 * it for the current set of actions.
 *
 * Why no `endedAt` field: macOS `date` doesn't support `%N` so we'd
 * be limited to second-precision, which causes negative durations
 * for actions that complete within the same wall-second they
 * started. The registry stamps `endedAt` from `done.json`'s file
 * mtime at read time instead — millisecond-precise, no shell
 * gymnastics, and equally accurate for runs that completed while
 * wt was down (`mtimeMs` is set when the trap creates the file).
 *
 * Signal flow: `tmux kill-session` sends SIGHUP to the pane process
 * (this script). Bash exits, EXIT trap fires, done.json is written.
 * Children (claude, pnpm, node, …) inherit the SIGHUP via the tmux
 * pane's session relationship, so they go down with the bash leader
 * — no orphan zsh wrappers like the pre-tmux runner left behind.
 */
const WRAPPER_SCRIPT = `#!/usr/bin/env bash
# wt action wrapper. Args: <run_dir> <argv...>
# Generated by core/action-tmux.ts; do not edit by hand.

run_dir="$1"; shift

cleanup() {
  ec=$?
  printf '{"exitCode":%d}\\n' "$ec" > "$run_dir/done.json"
}
# Bash 3.2 (macOS-default /bin/bash) doesn't always run EXIT on
# signal-driven exits. List the signals tmux is likely to send
# explicitly so the trap fires regardless of bash version.
trap cleanup EXIT HUP TERM INT QUIT

"$@" >> "$run_dir/stream.log" 2>> "$run_dir/stderr.log"
`;

function cacheDir(): string {
  const dir = join(homedir(), ".cache", "wt");
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Write the wrapper to disk if it differs from what's already there;
 * return its absolute path. Idempotent. The bash wrapper itself never
 * changes between runs of one wt build, but a wt upgrade that ships
 * a new wrapper string rolls it forward atomically.
 */
export function ensureWrapper(): string {
  const path = join(cacheDir(), "wt-action-wrapper.sh");
  let prev = "";
  try {
    prev = readFileSync(path, "utf8");
  } catch {
    // first run
  }
  if (prev !== WRAPPER_SCRIPT) {
    writeFileSync(path, WRAPPER_SCRIPT, { mode: 0o755 });
  }
  return path;
}

/** Bare action session name for a slug. */
export function actionSessionName(slug: string): string {
  return `${slug}${ACTION_SUFFIX}`;
}

/**
 * Spawn a detached tmux session that runs the wrapper with the given
 * inner argv. Sync because `tmux new-session -d` exits immediately on
 * success (sub-100ms steady state), and `actionRegistry.start` is a
 * sync entry point — wrapping in async here would force every caller
 * up through `launchAction` to thread it.
 *
 * The session is created with `new-session -d` (detached), no `-A`
 * (we deliberately don't want attach-or-create — concurrent starts
 * on the same slug should fail loudly so the registry's "one running
 * per slug" guard is meaningful at the tmux layer too).
 */
export function startActionSession(opts: {
  slug: string;
  cwd: string;
  runDir: string;
  argv: readonly string[];
}): { ok: true } | { ok: false; reason: string } {
  const { slug, cwd, runDir, argv } = opts;
  const wrapper = ensureWrapper();
  const name = actionSessionName(slug);
  const proc = Bun.spawnSync(
    [
      "tmux",
      "-L",
      TMUX_SOCKET,
      "new-session",
      "-d",
      "-s",
      name,
      "-c",
      cwd,
      "bash",
      wrapper,
      runDir,
      ...argv,
    ],
    {
      stdout: "ignore",
      stderr: "pipe",
      // Inherit env so the inner command sees the same PATH, $SHELL,
      // and any user-set env vars (CLAUDE_API_KEY, etc.). We deliberately
      // don't strip TMUX here the way `attachOrCreate` does for claude's
      // colour downgrade — actions don't render TUIs, and stripping would
      // break tmux-aware tools the user may have wired into a shell action.
    },
  );
  if (proc.exitCode === 0) return { ok: true };
  const errText = (proc.stderr ?? "").toString().trim();
  const reason = errText || `tmux new-session exited ${proc.exitCode}`;
  log.warn("startActionSession failed", {
    slug,
    code: proc.exitCode,
    reason,
  });
  return { ok: false, reason };
}

/**
 * Kill one slug's action session. Idempotent — silently no-ops when
 * the session doesn't exist or the server isn't running. Triggers
 * the wrapper's EXIT trap, which writes `done.json`.
 *
 * Sync because the registry's `kill()` finalizes state synchronously
 * (closes tail/done watchers, persists meta, commits status flip)
 * and needs the tmux session gone before returning so a follow-up
 * `start()` for the same slug doesn't collide on the session name.
 * `tmux kill-session` is fast (sub-100ms steady state); the wrapper's
 * EXIT trap fires asynchronously after.
 */
export function killActionSession(slug: string): void {
  Bun.spawnSync(
    [
      "tmux",
      "-L",
      TMUX_SOCKET,
      "kill-session",
      "-t",
      `=${actionSessionName(slug)}`,
    ],
    { stdout: "ignore", stderr: "ignore" },
  );
}

/**
 * Whether an action session exists right now for `slug`. Used by the
 * boot reconciler when deciding whether a run with `status="running"`
 * on disk is actually still running, or whether the wrapper crashed
 * without firing the EXIT trap.
 */
export async function actionSessionExists(slug: string): Promise<boolean> {
  const proc = Bun.spawn(
    [
      "tmux",
      "-L",
      TMUX_SOCKET,
      "has-session",
      "-t",
      `=${actionSessionName(slug)}`,
    ],
    { stdout: "ignore", stderr: "ignore" },
  );
  const code = await proc.exited;
  return code === 0;
}
