/**
 * Per-session summary snippets read from the session's own jsonl. Three
 * signals in priority order, each generated by claude itself:
 *
 *   1. `ai-title.aiTitle` — claude's auto-generated short title (what
 *      the `/resume` picker renders). Highest signal; not always
 *      present (older sessions, very short ones).
 *   2. `system.away_summary.content` — claude's narrative recap
 *      written when the conversation is auto-compacted. Multi-line;
 *      we take it whole, capped.
 *   3. `last-prompt.lastPrompt` — the user's most recent prompt. Not
 *      a "summary" per se but the best "what is this session about"
 *      hint when nothing higher exists.
 *
 * The reader walks each jsonl backward from EOF in `CHUNK_BYTES`
 * (256 KB) slices up to `MAX_SCAN_BYTES` (4 MB) total. Long-running
 * sessions accumulate file-history-snapshot padding near the tail with
 * no conversation entries, so a single fixed tail window misses them;
 * the chunked walk steps past that padding. We short-circuit as soon
 * as an `ai-title` is found (the highest tier), and never let an
 * earlier-found lower tier shadow a later-found higher tier.
 *
 * Output text is sanitized for control / ANSI escape sequences and
 * length-capped before caching, since the source includes
 * model-written prose and user-typed prompts that get rendered raw in
 * the TUI summary panel.
 *
 * (mtime, size) memoization keeps repeated picker opens essentially
 * free; we never cache on error so a transient read failure can't
 * poison the entry.
 */
import { closeSync, openSync, statSync } from "node:fs";

import { sessionJsonlPath } from "./claude.ts";
import { AWAY_RECAP_HINT_RE, asObj } from "./claude-events.ts";
import { createLogger } from "./logger.ts";
import { readFdSlice } from "./tail-util.ts";

const log = createLogger("[claude-summaries]");

const CHUNK_BYTES = 256 * 1024;
const MAX_SCAN_BYTES = 4 * 1024 * 1024;
const PROMPT_TRUNCATE = 240;
const AWAY_TRUNCATE = 800;
/** Pre-built once; collapsing control bytes (TAB and NEWLINE kept) +
 *  CSI / OSC escape introducers we'd never want to forward to the
 *  terminal renderer. */
const CONTROL_RE = /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g;
/** Strict UUID v1-v5 shape. The summary reader joins arbitrary
 *  `sessionId` strings into a filesystem path; the only legitimate
 *  caller passes UUIDs from `wtSessionUuid`, but the guard means a
 *  future caller that accidentally hands the registry's `sessionId`
 *  (parsed from untrusted JSON) can't traverse out of the project dir. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export type SessionSummary = {
  /** Sanitized, length-capped display text. */
  text: string;
  /** Which signal produced it — drives the dim source label. */
  source: "ai-title" | "away_summary" | "last-prompt";
};

const SOURCE_RANK: Record<SessionSummary["source"], number> = {
  "ai-title": 0,
  away_summary: 1,
  "last-prompt": 2,
};

type CacheEntry = {
  mtimeMs: number;
  size: number;
  summary: SessionSummary | null;
};
/** FIFO-bounded cache; `cache.keys().next()` returns insertion order, so
 *  the oldest write is evicted. Not LRU — accessed entries don't get
 *  re-promoted — but the (mtime, size) check inside `readSummary`
 *  already carries the "free repeat open" guarantee. */
const cache = new Map<string, CacheEntry>();
const CACHE_MAX = 256;

function sanitize(s: string): string {
  return s.replace(CONTROL_RE, "");
}

function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max)}…` : s;
}

/**
 * Walk `text` from the end and return the highest-signal summary
 * present. `ai-title` short-circuits the scan; the other tiers fall
 * through so a single pass picks the best the chunk has. `partialHead`
 * skips a possibly-truncated first line so we don't half-parse a JSON
 * record split mid-stream.
 *
 * Substring gates are anchored on `"type":"..."` (and `"subtype":"..."`
 * for away_summary) to avoid matching the literal kind name embedded
 * inside a user prompt or model output.
 */
function findLatestSummary(
  text: string,
  partialHead: boolean,
): SessionSummary | null {
  const lines = text.split("\n");
  const stop = partialHead ? 1 : 0;
  let away: SessionSummary | null = null;
  let prompt: SessionSummary | null = null;
  for (let i = lines.length - 1; i >= stop; i--) {
    const line = lines[i];
    if (!line) continue;
    const isAiTitle = line.includes('"type":"ai-title"');
    const isAway =
      !isAiTitle && line.includes('"subtype":"away_summary"');
    const isPrompt =
      !isAiTitle && !isAway && line.includes('"type":"last-prompt"');
    if (!isAiTitle && !isAway && !isPrompt) continue;
    let obj: Record<string, unknown> | null;
    try {
      obj = asObj(JSON.parse(line));
    } catch {
      continue;
    }
    if (!obj) continue;
    if (isAiTitle && obj.type === "ai-title") {
      const t = obj.aiTitle;
      if (typeof t === "string") {
        const text = sanitize(t).trim();
        if (text.length > 0) {
          return { text: truncate(text, PROMPT_TRUNCATE), source: "ai-title" };
        }
      }
      continue;
    }
    if (isAway && obj.type === "system" && obj.subtype === "away_summary") {
      if (away !== null) continue;
      const content = obj.content;
      if (typeof content === "string") {
        const text = sanitize(content)
          .replace(AWAY_RECAP_HINT_RE, "")
          .trim();
        if (text.length > 0) {
          away = { text: truncate(text, AWAY_TRUNCATE), source: "away_summary" };
        }
      }
      continue;
    }
    if (isPrompt && obj.type === "last-prompt") {
      if (prompt !== null) continue;
      const t = obj.lastPrompt;
      if (typeof t === "string") {
        const text = sanitize(t).trim();
        if (text.length > 0) {
          prompt = { text: truncate(text, PROMPT_TRUNCATE), source: "last-prompt" };
        }
      }
    }
  }
  return away ?? prompt;
}

function readSummary(path: string): SessionSummary | null {
  let mtimeMs = 0;
  let size = 0;
  try {
    const st = statSync(path);
    if (!st.isFile()) return null;
    mtimeMs = st.mtimeMs;
    size = st.size;
  } catch {
    cache.delete(path);
    return null;
  }
  if (size === 0) return null;

  const cached = cache.get(path);
  if (cached && cached.mtimeMs === mtimeMs && cached.size === size) {
    return cached.summary;
  }

  let summary: SessionSummary | null = null;
  let fd: number;
  try {
    fd = openSync(path, "r");
  } catch {
    // File disappeared between stat and open. Drop any stale entry so
    // a future call retries fresh; don't write a poisoned `null`
    // pinned to a (mtimeMs, size) that no longer corresponds to disk.
    cache.delete(path);
    return null;
  }
  let scanErrored = false;
  try {
    let end = size;
    const stopAt = Math.max(0, size - MAX_SCAN_BYTES);
    while (end > stopAt) {
      const start = Math.max(stopAt, end - CHUNK_BYTES);
      const len = end - start;
      const found = findLatestSummary(readFdSlice(fd, start, len), start > 0);
      if (found) {
        // Across chunks, promote to any strictly higher-priority
        // source. Within a chunk, `findLatestSummary` already returns
        // the best — but a later (later-in-time) `last-prompt` chunk
        // mustn't shadow an earlier (older-in-time) `away_summary`
        // chunk just because we found it first.
        if (!summary || SOURCE_RANK[found.source] < SOURCE_RANK[summary.source]) {
          summary = found;
        }
        if (summary.source === "ai-title") break;
      }
      end = start;
    }
  } catch (err) {
    scanErrored = true;
    log.warn("read failed", {
      path,
      err: err instanceof Error ? err.message : String(err),
    });
  } finally {
    try {
      closeSync(fd);
    } catch {
      // ignore
    }
  }

  // Skip caching on read error so a transient failure (file truncated
  // mid-scan, IO blip) doesn't pin a stale `null` for this (mtime,
  // size) until the file gets rewritten.
  if (!scanErrored) {
    if (cache.size >= CACHE_MAX) {
      const first = cache.keys().next().value;
      if (first !== undefined) cache.delete(first);
    }
    cache.set(path, { mtimeMs, size, summary });
  }
  return summary;
}

/**
 * Best-available summary per (wtPath, sessionId). Sessions with no
 * usable signal (jsonl empty / missing / all-padding within budget)
 * map to `null`. Reads are sequential — at most a handful of sessions
 * per worktree — and the cache makes repeated picker opens essentially
 * free.
 *
 * Invalid sessionIds (non-UUID) map to `null` without touching the
 * filesystem; safe default for any callers that hand us strings
 * derived from untrusted JSON.
 */
export function readSummariesForSessions(
  wtPath: string,
  sessionIds: readonly string[],
): Record<string, SessionSummary | null> {
  const out: Record<string, SessionSummary | null> = {};
  for (const id of sessionIds) {
    if (!UUID_RE.test(id)) {
      out[id] = null;
      continue;
    }
    out[id] = readSummary(sessionJsonlPath(wtPath, id));
  }
  return out;
}
