/**
 * Config loader.
 *
 * Reads `config.toml` from (in order):
 *   1. `$WT_CONFIG` (explicit override)
 *   2. `$XDG_CONFIG_HOME/wt/config.toml`
 *   3. `~/.config/wt/config.toml`
 *
 * Required fields have no default — the loader collects every missing
 * or malformed field and exits with one human-readable error before
 * the TUI ever starts. Generic defaults (branch.base, slug_max_len,
 * etc.) are filled in transparently; values derived from the user's
 * branch prefix (stage.prefix, stage.default_personal) are computed
 * when omitted.
 *
 * The whole config resolves once at import time and is exposed as a
 * frozen `config` object plus named constants in `paths.ts`. Hot
 * reload is intentionally not supported — the TUI reads a stable
 * snapshot for its lifetime.
 */
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const HOME = homedir();

function expandHome(p: string): string {
  if (p === "~") return HOME;
  if (p.startsWith("~/")) return join(HOME, p.slice(2));
  return p;
}

export type SstConfig = {
  stateBucket: string;
  statePrefix: string;
  awsProfile: string;
  /** Files in the main clone regenerated by `sst` runs; restored before fetch. */
  autoRegenPaths: readonly string[];
};

export type LinearConfig = {
  workspace: string;
};

export type GithubConfig = {
  /**
   * Glob patterns matched against check context names (CheckRun.name /
   * StatusContext.context). Matching contexts are dropped from the PR
   * checks rollup, so non-CI bots like CodeRabbit and Graphite don't
   * flip the badge. Case-insensitive; `*` is the only wildcard.
   */
  ignoredChecks: readonly string[];
};

export type DiffConfig = {
  /**
   * Shell command launched on F11 inside the selected worktree's path.
   * Runs via `$SHELL -lc` (bash fallback) so pipes (`git diff | delta --paging=always`)
   * and aliases work. Defaults to `gitu`; users can swap in `lazygit`,
   * `tig status`, or anything else they prefer.
   */
  command: string;
};

export type AiConfig = {
  /** OpenAI-compatible endpoint (no trailing slash). LM Studio defaults to http://127.0.0.1:1234. */
  endpoint: string;
  /** Model id as exposed by the endpoint (LM Studio shows it verbatim). */
  model: string;
  /** Soft budget for the prompt; we drop diff hunks largest-first to stay under it. */
  maxInputTokens: number;
  /** Per-request timeout in ms. */
  timeoutMs: number;
};

/**
 * Pre-built action surfaced by the `!` modal. Two flavors:
 *
 *   - `claude`: launches `claude -p` with the configured prompt; the
 *     edit modal exposes an extras textarea that gets appended.
 *   - `shell`: launches `$SHELL -lc <shell>` in the worktree path; the
 *     edit modal is skipped and Enter launches directly.
 *
 * Both `prompt` and `shell` (and the user-typed extras) support
 * `{{var}}` substitution. Vars are populated per-launch from the row
 * — see `buildActionVars` in `tui/app.tsx` for the full set. Unknown
 * vars pass through unchanged so typos surface in the rendered prompt.
 *
 * When `[[actions]]` is absent the built-in defaults take effect; when
 * it's present (even with one entry), the user's list is authoritative
 * — the way to drop a default is to list everything except it.
 */
export type ActionDef =
  | { kind: "claude"; id: string; name: string; prompt: string }
  | { kind: "shell"; id: string; name: string; shell: string };

export type Config = {
  paths: {
    mainClone: string;
    worktreeRoot: string;
    logDir: string;
    /** Daily structured log files written by `core/logger.ts`. Derived from `logDir`. */
    appLogDir: string;
    lockDir: string;
    /** SQLite blob holding the persisted TanStack Query cache. */
    cacheDb: string;
  };
  branch: {
    prefix: string;
    base: string;
    /** Regex (no flags) matching an issue ID at the start of a slug. */
    idPattern: string;
    slugMaxLen: number;
  };
  stage: {
    prefix: string;
    /** Stage name reserved for the user's personal env; excluded from orphans. */
    defaultPersonal: string;
    /** Public domain for stage URLs; null = stage URLs are not constructed. */
    domain: string | null;
  };
  lifecycle: {
    envFilesToCopy: readonly string[];
  };
  sst: SstConfig | null;
  linear: LinearConfig | null;
  ai: AiConfig | null;
  diff: DiffConfig;
  github: GithubConfig;
  actions: readonly ActionDef[];
  ui: {
    /** Detail-pane row order. Unknown ids are ignored, missing ones hidden. */
    rows: readonly string[];
  };
};

/** Generic-only defaults. Anything specific to a user/repo lives in `config.toml`. */
const GENERIC_DEFAULTS = {
  branch: {
    base: "main",
    // Matches Linear/Jira/Shortcut-style team-id prefixes (eng-1234, INF-99…).
    idPattern: "^[a-z]+-(\\d+)(?:-|$)",
    slugMaxLen: 50,
  },
  lifecycle: {
    envFilesToCopy: [".env"] as const,
  },
  paths: {
    logDir: join(HOME, ".cache", "wt", "logs"),
    lockDir: join(HOME, ".cache", "wt", "locks"),
    cacheDb: join(HOME, ".cache", "wt", "cache.sqlite"),
  },
  // SST v3 convention: per-stage Pulumi state file lives at
  // `<state_prefix><stage>.json`. The default file regenerated per
  // stage is `sst-env.d.ts`.
  sst: {
    autoRegenPaths: ["sst-env.d.ts"] as const,
  },
  diff: {
    command: "gitu",
  },
  ai: {
    maxInputTokens: 8000,
    // Local LLMs running on CPU/Metal can take 30s+ on a cold cache,
    // and the first request after model load is slower still. 2 min
    // gives Gemma-class models headroom; users on faster hardware can
    // dial down via [ai].timeout_ms.
    timeoutMs: 120_000,
  },
  ui: {
    rows: ["branch", "base", "linear", "stage", "pr", "claude", "git"] as const,
  },
  actions: [
    {
      kind: "claude" as const,
      id: "rebase-main",
      name: "Rebase on base",
      prompt:
        "Please rebase this branch on origin/{{base_branch}} and intelligently resolve any conflicts that come up. Push when you're done.",
    },
    {
      kind: "claude" as const,
      id: "address-review",
      name: "Address PR review",
      prompt:
        "Check the requested changes from the review on the PR for this branch and address them. Push the changes, then resolve the review threads (no reply comments). When done, request a re-review from the original reviewers.",
    },
  ] as const,
};

function configPath(): { path: string; present: boolean } {
  const explicit = process.env.WT_CONFIG;
  if (explicit) {
    const p = expandHome(explicit);
    return { path: p, present: existsSync(p) };
  }
  const xdg = process.env.XDG_CONFIG_HOME;
  const dir = xdg ? expandHome(xdg) : join(HOME, ".config");
  const p = join(dir, "wt", "config.toml");
  return { path: p, present: existsSync(p) };
}

type Raw = Record<string, unknown>;

function obj(v: unknown): Raw | null {
  return v && typeof v === "object" && !Array.isArray(v) ? (v as Raw) : null;
}

function strArr(v: unknown, fallback: readonly string[]): readonly string[] {
  if (!Array.isArray(v)) return fallback;
  const out: string[] = [];
  for (const x of v) if (typeof x === "string") out.push(x);
  return out;
}

class Errors {
  private list: string[] = [];
  add(msg: string) {
    this.list.push(msg);
  }
  /** Read a required string field; record an error and return "" on miss. */
  reqStr(parent: Raw | null, section: string, key: string): string {
    const v = parent?.[key];
    if (typeof v === "string" && v.length > 0) return v;
    this.add(`${section}.${key} is required`);
    return "";
  }
  optStr(parent: Raw | null, key: string, fallback: string): string {
    const v = parent?.[key];
    return typeof v === "string" && v.length > 0 ? v : fallback;
  }
  optStrOrNull(parent: Raw | null, key: string): string | null {
    const v = parent?.[key];
    return typeof v === "string" && v.length > 0 ? v : null;
  }
  optNum(parent: Raw | null, key: string, fallback: number): number {
    const v = parent?.[key];
    return typeof v === "number" && Number.isFinite(v) ? v : fallback;
  }
  flush(configFile: string): void {
    if (this.list.length === 0) return;
    const lines = this.list.map((l) => `  - ${l}`).join("\n");
    process.stderr.write(
      `wt: invalid config at ${configFile}\n${lines}\n` +
        `\nSee src/core/config.ts for the full schema.\n`,
    );
    process.exit(1);
  }
}

function loadRaw(path: string, present: boolean, errs: Errors): Raw {
  if (!present) {
    errs.add(`config file not found at ${path}`);
    return {};
  }
  try {
    const text = readFileSync(path, "utf8");
    const parsed = Bun.TOML.parse(text);
    return obj(parsed) ?? {};
  } catch (err) {
    errs.add(`failed to parse: ${(err as Error).message}`);
    return {};
  }
}

function build(raw: Raw, errs: Errors): Config {
  const paths = obj(raw.paths);
  const branch = obj(raw.branch);
  const stage = obj(raw.stage);
  const lifecycle = obj(raw.lifecycle);
  const deploy = obj(raw.deploy);
  const sstRaw = deploy ? obj(deploy.sst) : null;
  const tracker = obj(raw.issue_tracker);
  const linearRaw = tracker ? obj(tracker.linear) : null;
  const ui = obj(raw.ui);

  const branchPrefix = errs.reqStr(branch, "branch", "prefix");
  const branchBase = errs.optStr(branch, "base", GENERIC_DEFAULTS.branch.base);
  const idPattern = errs.optStr(branch, "id_pattern", GENERIC_DEFAULTS.branch.idPattern);
  const slugMaxLen = errs.optNum(branch, "slug_max_len", GENERIC_DEFAULTS.branch.slugMaxLen);

  const mainClone = expandHome(errs.reqStr(paths, "paths", "main_clone"));
  const worktreeRoot = expandHome(errs.reqStr(paths, "paths", "worktree_root"));
  const logDir = expandHome(errs.optStr(paths, "log_dir", GENERIC_DEFAULTS.paths.logDir));
  // Sibling subdir for structured app logs — keeps daily `wt-*.log`
  // files separate from the per-worktree `<slug>-*.log` destroy logs
  // that `wt logs <slug>` reads. Not user-configurable; fold into
  // `log_dir` if the user moved that.
  const appLogDir = join(logDir, "app");
  const lockDir = expandHome(errs.optStr(paths, "lock_dir", GENERIC_DEFAULTS.paths.lockDir));
  const cacheDb = expandHome(errs.optStr(paths, "cache_db", GENERIC_DEFAULTS.paths.cacheDb));

  // Stage prefix derives from branch.prefix when omitted — the
  // overwhelmingly common shape is `<branch.prefix>-<stage>`. Same
  // for the personal stage name, which is just the bare prefix.
  const stagePrefix = errs.optStr(stage, "prefix", `${branchPrefix}-`);
  const stageDefault = errs.optStr(stage, "default_personal", branchPrefix);
  const stageDomain = errs.optStrOrNull(stage, "domain");

  const envFiles = strArr(lifecycle?.env_files_to_copy, GENERIC_DEFAULTS.lifecycle.envFilesToCopy);

  // SST and Linear are entirely optional — absence of the section
  // disables the integration. When the section IS present, every
  // required field within it must be set.
  const sst: SstConfig | null = sstRaw === null
    ? null
    : {
      stateBucket: errs.reqStr(sstRaw, "deploy.sst", "state_bucket"),
      statePrefix: errs.reqStr(sstRaw, "deploy.sst", "state_prefix"),
      awsProfile: errs.reqStr(sstRaw, "deploy.sst", "aws_profile"),
      autoRegenPaths: strArr(sstRaw.auto_regen_paths, GENERIC_DEFAULTS.sst.autoRegenPaths),
    };

  const linear: LinearConfig | null = linearRaw === null
    ? null
    : { workspace: errs.reqStr(linearRaw, "issue_tracker.linear", "workspace") };

  const aiRaw = obj(raw.ai);
  const ai: AiConfig | null = aiRaw === null
    ? null
    : {
      endpoint: errs.reqStr(aiRaw, "ai", "endpoint").replace(/\/+$/, ""),
      model: errs.reqStr(aiRaw, "ai", "model"),
      maxInputTokens: errs.optNum(aiRaw, "max_input_tokens", GENERIC_DEFAULTS.ai.maxInputTokens),
      timeoutMs: errs.optNum(aiRaw, "timeout_ms", GENERIC_DEFAULTS.ai.timeoutMs),
    };

  const diffRaw = obj(raw.diff);
  const diff: DiffConfig = {
    command: errs.optStr(diffRaw, "command", GENERIC_DEFAULTS.diff.command),
  };

  const rows = strArr(ui?.rows, GENERIC_DEFAULTS.ui.rows);

  const githubRaw = obj(raw.github);
  const github: GithubConfig = {
    ignoredChecks: strArr(githubRaw?.ignored_checks, []),
  };

  // [[actions]] is fully replaced when the user provides any entries
  // (even just one) — otherwise the built-in defaults apply. That way
  // a user can drop a default they don't want simply by listing the
  // ones they keep.
  const actions = parseActions(raw.actions, errs);

  return {
    paths: { mainClone, worktreeRoot, logDir, appLogDir, lockDir, cacheDb },
    branch: { prefix: branchPrefix, base: branchBase, idPattern, slugMaxLen },
    stage: { prefix: stagePrefix, defaultPersonal: stageDefault, domain: stageDomain },
    lifecycle: { envFilesToCopy: envFiles },
    sst,
    linear,
    ai,
    diff,
    github,
    actions,
    ui: { rows },
  };
}

function parseActions(raw: unknown, errs: Errors): readonly ActionDef[] {
  if (raw === undefined) return GENERIC_DEFAULTS.actions;
  if (!Array.isArray(raw)) {
    errs.add("actions must be a TOML array of [[actions]] tables");
    return GENERIC_DEFAULTS.actions;
  }
  const out: ActionDef[] = [];
  const seenIds = new Set<string>();
  for (let i = 0; i < raw.length; i++) {
    const entry = obj(raw[i]);
    const tag = `actions[${i}]`;
    if (!entry) {
      errs.add(`${tag} must be a table`);
      continue;
    }
    const id = errs.reqStr(entry, tag, "id");
    const name = errs.reqStr(entry, tag, "name");
    if (!id || !name) continue;
    if (seenIds.has(id)) {
      errs.add(`${tag}.id "${id}" is duplicated`);
      continue;
    }
    const promptVal = entry.prompt;
    const shellVal = entry.shell;
    const hasPrompt = typeof promptVal === "string" && promptVal.length > 0;
    const hasShell = typeof shellVal === "string" && shellVal.length > 0;
    // Distinguish "wrong type / empty" from "missing entirely" so the
    // error names the real problem instead of demanding a field the
    // user already tried to set.
    if (promptVal !== undefined && !hasPrompt) {
      errs.add(`${tag}.prompt must be a non-empty string`);
      continue;
    }
    if (shellVal !== undefined && !hasShell) {
      errs.add(`${tag}.shell must be a non-empty string`);
      continue;
    }
    if (hasPrompt && hasShell) {
      errs.add(`${tag} must set exactly one of "prompt" or "shell", not both`);
      continue;
    }
    if (!hasPrompt && !hasShell) {
      errs.add(`${tag} must set one of "prompt" or "shell"`);
      continue;
    }
    seenIds.add(id);
    if (hasPrompt) {
      out.push({ kind: "claude", id, name, prompt: promptVal as string });
    } else {
      out.push({ kind: "shell", id, name, shell: shellVal as string });
    }
  }
  return out;
}

function load(): { cfg: Config; path: string } {
  const { path, present } = configPath();
  const errs = new Errors();
  const raw = loadRaw(path, present, errs);
  const cfg = build(raw, errs);
  errs.flush(path);
  return { cfg, path };
}

const loaded = load();

export const config: Config = Object.freeze(loaded.cfg) as Config;
/** Absolute path of the TOML file the config was loaded from. */
export const configFilePath: string = loaded.path;

/**
 * Assert SST is configured and return its config. Call from code paths
 * that only make sense with `[deploy.sst]` set (the `wt stages` command,
 * `core/sst.ts` helpers). Throws a user-readable error if not.
 */
export function requireSst(): SstConfig {
  if (!config.sst) {
    throw new Error("[deploy.sst] is not configured in config.toml");
  }
  return config.sst;
}
